//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LanguageDescription
    {
        public int LD_ID { get; set; }
        public Nullable<int> ID_LanguageTable { get; set; }
        public string LD_VI { get; set; }
        public string LD_EN { get; set; }
    }
}
