//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Card
    {
        public int ID { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public Nullable<double> Card_TotalPrice { get; set; }
        public Nullable<double> Card_TotalPriceSelloff { get; set; }
        public Nullable<double> Card_TraveliingFee { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsConfirmSucess { get; set; }
        public Nullable<int> ID_Payments { get; set; }
    }
}
