//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductHistory
    {
        public int ProductHistory_ID { get; set; }
        public Nullable<System.DateTime> ProductHistory_Date { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> ID_ProductionUnit { get; set; }
        public Nullable<double> ProductHistory_Price { get; set; }
        public string IsDelete { get; set; }
    }
}
