//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Branch
    {
        public int Branch_ID { get; set; }
        public string Branch_Name { get; set; }
        public string Branch_Code { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
