//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubSubject
    {
        public int Sub_ID { get; set; }
        public Nullable<int> ID_Subject { get; set; }
        public string Sub_SubjectName { get; set; }
        public string Sub_Description { get; set; }
        public string Sub_Url { get; set; }
        public string Sub_Keyword { get; set; }
        public string Sub_Picture { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
