//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Subject
    {
        public int ID { get; set; }
        public string SubjectName { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberPosts { get; set; }
        public string Picture { get; set; }
        public string Url { get; set; }
        public string Keyword { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
