//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita_Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tvita {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tvita() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tvita_Test.Tvita", typeof(Tvita).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về T.Vita.
        /// </summary>
        public static string AboutTVita {
            get {
                return ResourceManager.GetString("AboutTVita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ: Tầng 3, Tòa Artex, Số 172 Ngọc Khánh, Q. Ba Đình, Hà Nội | Điện thoại: 024.3 244 4691.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát triển.
        /// </summary>
        public static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi.
        /// </summary>
        public static string Contactus {
            get {
                return ResourceManager.GetString("Contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản quyền thuộc T.Vita.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cộng đồng.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân phối.
        /// </summary>
        public static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội địa.
        /// </summary>
        public static string Domestic {
            get {
                return ResourceManager.GetString("Domestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nông trường.
        /// </summary>
        public static string Farms {
            get {
                return ResourceManager.GetString("Farms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các vùng nguyên liệu và nông trường của T.Vita sẽ được phân bổ tại vùng cao nguyên – trung du và đồng bằng, đảm bảo sự đa dạng các chủng loại sản phẩm quanh năm, đồng thời có khí hậu thổ nhưỡng phù hợp với từng loại cây trồng cho ra đời những sản phẩm có năng xuất chất lượng Các vùng nguyên liệu và nông trường của T.Vita sẽ được phân bổ tại vùng cao nguyên – trung du và đồng bằng, đảm bảo sự đa dạng các chủng loại sản phẩm quanh năm, đồng thời có khí hậu thổ nhưỡng phù hợp với từng loại cây trồng cho ra đời [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FarmsDes {
            get {
                return ResourceManager.GetString("FarmsDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm tươi.
        /// </summary>
        public static string FreshProducts {
            get {
                return ResourceManager.GetString("FreshProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trái cây.
        /// </summary>
        public static string Fruits {
            get {
                return ResourceManager.GetString("Fruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rau ăn quả.
        /// </summary>
        public static string FruitVegetables {
            get {
                return ResourceManager.GetString("FruitVegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vào bếp.
        /// </summary>
        public static string GotoKitchen {
            get {
                return ResourceManager.GetString("GotoKitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử hình thành.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức nổi bật.
        /// </summary>
        public static string HotNews {
            get {
                return ResourceManager.GetString("HotNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn bảo quản.
        /// </summary>
        public static string Howtopreserve {
            get {
                return ResourceManager.GetString("Howtopreserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        public static string Howtouse {
            get {
                return ResourceManager.GetString("Howtouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên của bạn.
        /// </summary>
        public static string InputYourName {
            get {
                return ResourceManager.GetString("InputYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rau ăn lá.
        /// </summary>
        public static string LeafyVegetables {
            get {
                return ResourceManager.GetString("LeafyVegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiều bài viết hơn.
        /// </summary>
        public static string LoadMoreArticles {
            get {
                return ResourceManager.GetString("LoadMoreArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiều tin tức hơn.
        /// </summary>
        public static string LoadMoreNews {
            get {
                return ResourceManager.GetString("LoadMoreNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiều sản phẩm hơn.
        /// </summary>
        public static string LoadMoreProduct {
            get {
                return ResourceManager.GetString("LoadMoreProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất xứ.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc tế.
        /// </summary>
        public static string Overseas {
            get {
                return ResourceManager.GetString("Overseas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy cách đóng gói.
        /// </summary>
        public static string Packingspecification {
            get {
                return ResourceManager.GetString("Packingspecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sau thu hoạch.
        /// </summary>
        public static string Postharvest {
            get {
                return ResourceManager.GetString("Postharvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ sau thu hoạch.
        /// </summary>
        public static string PostharvestTechnology {
            get {
                return ResourceManager.GetString("PostharvestTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm chế biến.
        /// </summary>
        public static string ProcessedProducts {
            get {
                return ResourceManager.GetString("ProcessedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhằm góp phần tăng giá trị cho các thương hiệu và sản phẩm nông nghiệp Việt Nam đồng thời mang lại sự tiện lợi và an tâm cho người nội trợ, T.Vita đặc biệt chú trọng phát triển dòng sản phẩm chế biến.
        ///                    Bằng các công nghệ bảo quản và chế biến tiên tiến nhất của Châu Âu như dây chuyền sơ chế tự động (cắt, gọt, rửa), chuỗi cung ứng lạnh, công nghệ hấp - sấy thăng hoa giúp giữ tối đa các dưỡng chất trong nguyên liệu; các sản phẩm sơ chế và chế biến sẵn của T.Vita như salad rau củ quả, rau củ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProcessNew {
            get {
                return ResourceManager.GetString("ProcessNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin sản phẩm.
        /// </summary>
        public static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ sản xuất.
        /// </summary>
        public static string ProductionTechnology {
            get {
                return ResourceManager.GetString("ProductionTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SẢN PHẨM.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn chất lượng.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm cùng loại.
        /// </summary>
        public static string RelatedProduct {
            get {
                return ResourceManager.GetString("RelatedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rau ăn củ.
        /// </summary>
        public static string RootVegetables {
            get {
                return ResourceManager.GetString("RootVegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nói chuyện với chúng tôi.
        /// </summary>
        public static string TalkWithMe {
            get {
                return ResourceManager.GetString("TalkWithMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ.
        /// </summary>
        public static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.Vita chú trọng đầu tư vào các mô hình trồng trọt công nghệ cao với hệ thống Nhà kính của Israel; Hệ thống tưới điều khiển tự động; Bộ giống chất lượng cao có khả năng kháng bệnh và chịu nhiệt từ các thương hiệu nổi tiếng thế giới..
        /// </summary>
        public static string TechnologyDes {
            get {
                return ResourceManager.GetString("TechnologyDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ.
        /// </summary>
        public static string TechTitle1 {
            get {
                return ResourceManager.GetString("TechTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản xuất.
        /// </summary>
        public static string TechTitle2 {
            get {
                return ResourceManager.GetString("TechTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nghệ.
        /// </summary>
        public static string TechTitle3 {
            get {
                return ResourceManager.GetString("TechTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sau thu hoạch.
        /// </summary>
        public static string TechTitle4 {
            get {
                return ResourceManager.GetString("TechTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập đoàn T&amp;T.
        /// </summary>
        public static string TTGroup {
            get {
                return ResourceManager.GetString("TTGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuỗi giá trị.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các sản phẩm T.Vita luôn đám bảo một chuỗi giá trị khép kín theo mô hình “từ trang trại đến bàn ăn”. Từ khi chỉ là hạt giống; cây sẽ được gieo trồng, chăm bón; khi đến mùa thu hoạch sẽ được chuyển đến Nhà máy để chế biến và đóng gói; từ đó các sản phẩm được chuyển đến các siêu thị, cửa hàng tới tay người tiêu dùng..
        /// </summary>
        public static string ValueChainDes {
            get {
                return ResourceManager.GetString("ValueChainDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tầm nhìn - Sứ mệnh.
        /// </summary>
        public static string VisionAndMission {
            get {
                return ResourceManager.GetString("VisionAndMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cùng T.Vita.
        /// </summary>
        public static string WithTvita {
            get {
                return ResourceManager.GetString("WithTvita", resourceCulture);
            }
        }
    }
}
