//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO
    {
        public int PO_ID { get; set; }
        public string Product_IDs { get; set; }
        public string Product_Names { get; set; }
        public Nullable<int> ProductionUnit_ID { get; set; }
        public string ProductionUnit_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> PO_Quantity { get; set; }
        public string PO_Unit { get; set; }
    }
}
