//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PU
    {
        public int PU_ID { get; set; }
        public string PU_Name { get; set; }
        public string PU_Content { get; set; }
        public string PU_Image { get; set; }
        public string PU_Address { get; set; }
        public string PU_Areas { get; set; }
        public string PU_CodeVietGap { get; set; }
        public string PU_Og { get; set; }
    }
}
