//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO
    {
        public int SO_ID { get; set; }
        public string Product_Names { get; set; }
        public string Product_IDs { get; set; }
        public Nullable<int> Store_ID { get; set; }
        public string Store_Name { get; set; }
        public Nullable<System.DateTime> SO_Date { get; set; }
        public Nullable<double> SO_Quantity { get; set; }
        public string SO_Unit { get; set; }
    }
}
