//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Store_ID { get; set; }
        public string Store_Name { get; set; }
        public string Store_Address { get; set; }
        public string Store_PhoneNum { get; set; }
        public string Store_Area { get; set; }
        public string Store_Rate { get; set; }
        public string Store_Type { get; set; }
    }
}
