//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Menu
    {
        public int Menu_ID { get; set; }
        public string Menu_Name { get; set; }
        public string Menu_Link { get; set; }
        public Nullable<int> Menu_ParentID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
