//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Post
    {
        public int Post_ID { get; set; }
        public Nullable<int> ID_SubSubject { get; set; }
        public string Post_Name { get; set; }
        public string Post_Description { get; set; }
        public string Post_Content { get; set; }
        public string Post_Picture { get; set; }
        public string Post_Video { get; set; }
        public string Post_Keyword { get; set; }
        public string Post_Url { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Post_DateCreated { get; set; }
        public string Post_Name_EN { get; set; }
        public string Post_Description_EN { get; set; }
        public string Post_Content_EN { get; set; }
    }
}
