//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductsInFarm
    {
        public int PIF_ID { get; set; }
        public Nullable<int> ID_ProductionUnit { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<double> PIF_AveragePrice { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
