//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LanguageTable
    {
        public int LT_ID { get; set; }
        public string LT_TableName { get; set; }
        public Nullable<int> LT_IdItem { get; set; }
    }
}
