//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Farm
    {
        public int Farm_ID { get; set; }
        public string Farm_Code { get; set; }
        public string Farm_Address { get; set; }
        public Nullable<double> Farm_Area { get; set; }
        public string Farm_Info { get; set; }
        public Nullable<double> Farm_Distance { get; set; }
        public string Farm_Territory { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
