//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderLandingPage
    {
        public int Order_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_PhoneNum { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_Note { get; set; }
        public Nullable<int> Product1 { get; set; }
        public Nullable<int> Product2 { get; set; }
        public Nullable<int> Product3 { get; set; }
        public Nullable<int> QuantityPro1 { get; set; }
        public Nullable<int> QuantityPro2 { get; set; }
        public Nullable<int> QuantityPro3 { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Time_Delivery { get; set; }
        public Nullable<bool> Is_Confirmed { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public string Customer_Email { get; set; }
    }
}
