//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Picture
    {
        public int Picture_ID { get; set; }
        public string Picture_Name { get; set; }
        public string Picture_Description { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Picture_Url { get; set; }
    }
}
