//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tvita.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GroupProduct
    {
        public int GroupProduct_ID { get; set; }
        public string GroupProduct_Code { get; set; }
        public string GroupProduct_Name { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string GroupProduct_Description { get; set; }
        public string GroupProduct_Picture { get; set; }
        public Nullable<int> ID_Branch { get; set; }
    }
}
